import {Activity,CircleDollarSign,Gauge,Sparkles,Target,TrendingUp} from "lucide-react";
import type {Account,Trade} from "@/types";
import {money,pct,stats} from "@/lib/utils";
import {Card,Pill} from "@/components/ui";
import {TradingCalendar} from "@/components/trading-calendar";
import {EquityChart,WinLoss} from "@/components/performance-charts";
export function DashboardOverview({trades,account,isDemo}:{trades:Trade[];account:Account;isDemo:boolean}){const s=stats(trades),today=new Date().toISOString().slice(0,10),todayP=trades.filter(t=>t.date===today).reduce((a,t)=>a+t.pnl,0),month=today.slice(0,7),monthP=trades.filter(t=>t.date.startsWith(month)).reduce((a,t)=>a+t.pnl,0),score=Math.round(Math.min(100,Math.max(0,s.winRate*.3+Math.min(s.profitFactor,3)*12+Math.max(0,s.averageRR)*10+25)));const cards=[["Current Balance",money(account.balance),CircleDollarSign,"primary"],["Today P/L",money(todayP),Activity,todayP>=0?"profit":"loss"],["Monthly P/L",money(monthP),TrendingUp,monthP>=0?"profit":"loss"],["Win Rate",pct(s.winRate),Target,"primary"]] as const;return <div className="space-y-5 animate-enter"><div className="flex flex-wrap items-end justify-between gap-3"><div className="flex items-center gap-3"><div><h2 className="text-2xl font-extrabold tracking-tight">Performance overview</h2><p className="mt-1 text-sm text-muted">See what is working and where your edge lives.</p></div>{isDemo&&<Pill tone="info">Demo data</Pill>}</div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,tone])=><Card key={label} className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs text-muted">{label}</p><b className="mt-2 block text-2xl">{value}</b></div><span className={`grid size-10 place-items-center rounded-xl ${tone==="profit"?"bg-bullish/10 text-bullish":tone==="loss"?"bg-bearish/10 text-bearish":"bg-primary/10 text-primary"}`}><Icon size={19}/></span></div></Card>)}</div>
 <TradingCalendar trades={trades}/>
 <div className="grid gap-5 xl:grid-cols-[1.5fr_.7fr]"><Card className="p-5"><h3 className="text-sm font-bold">Equity curve</h3><p className="mt-1 text-xs text-muted">Balance progression across closed trades</p><div className="mt-5"><EquityChart trades={trades} initial={account.initial}/></div></Card><Card className="p-5"><h3 className="text-sm font-bold">Win vs loss</h3><p className="mt-1 text-xs text-muted">Closed trade distribution</p><WinLoss trades={trades}/></Card></div>
 <div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card className="p-5"><h3 className="text-sm font-bold">Performance metrics</h3><div className="mt-4 grid grid-cols-2 sm:grid-cols-4">{[["Total P/L",money(s.totalPnl)],["Profit factor",s.profitFactor.toFixed(2)],["Average RR",s.averageRR.toFixed(2)+"R"],["Total trades",s.totalTrades],["Trading days",s.tradingDays],["Average win",money(s.averageWin)],["Average loss",money(s.averageLoss)],["Expectancy",money(s.expectancy)]].map(([l,v])=><div key={l} className="border-b border-border py-4"><p className="text-[10px] text-muted">{l}</p><b className="mt-1 block text-sm">{v}</b></div>)}</div></Card><Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-muted">Trading score</p><b>Process quality</b></div><Gauge className="text-primary"/></div><div className="my-6 text-center"><b className="text-5xl">{score}</b><span className="text-muted"> / 100</span></div><div className="rounded-xl border border-primary/15 bg-primary/5 p-3"><p className="flex items-center gap-2 text-[10px] font-bold text-[#9AB0FF]"><Sparkles size={13}/>AI QUICK INSIGHT</p><p className="mt-2 text-xs leading-5 text-muted">Patient London-session setups currently show the strongest journal results.</p></div></Card></div>
 </div>}
