"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {Download,FileText,Search} from "lucide-react";
import type {Trade} from "@/types";
import {Button,Card,Input,Pill,Select} from "@/components/ui";
import {money} from "@/lib/utils";
export function JournalTable({trades}:{trades:Trade[]}){
 const[q,setQ]=useState(""),[side,setSide]=useState("all"),[result,setResult]=useState("all"),[page,setPage]=useState(1);
 const filtered=useMemo(()=>trades.filter(t=>(!q||t.symbol.toLowerCase().includes(q.toLowerCase())||t.strategy.toLowerCase().includes(q.toLowerCase()))&&(side==="all"||t.direction===side)&&(result==="all"||t.status===result)).sort((a,b)=>b.date.localeCompare(a.date)),[trades,q,side,result]);
 const rows=filtered.slice((page-1)*10,page*10),pages=Math.max(1,Math.ceil(filtered.length/10));
 function csv(){const lines=[["Date","Symbol","Direction","Strategy","Entry","Exit","RR","PnL","Result"],...filtered.map(t=>[t.date,t.symbol,t.direction,t.strategy,t.entry,t.exit||"",t.rr,t.pnl,t.status])].map(r=>r.join(",")).join("\n"),blob=new Blob([lines],{type:"text/csv"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="fomotrade-journal.csv";a.click();URL.revokeObjectURL(url)}
 return <div className="space-y-5 animate-enter"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-extrabold">Trade history</h2><p className="mt-1 text-sm text-muted">Search, filter, review, and export every execution.</p></div><div className="flex gap-2"><Button kind="secondary" onClick={()=>window.print()}><FileText size={16}/>PDF</Button><Button kind="secondary" onClick={csv}><Download size={16}/>CSV</Button><Link href="/add-trade" className="inline-flex h-10 items-center rounded-xl bg-primary px-4 text-sm font-bold">Add trade</Link></div></div>
 <Card className="p-5"><div className="mb-5 flex flex-wrap gap-3"><div className="relative min-w-[240px] flex-1"><Search size={16} className="absolute left-3.5 top-3.5 text-muted"/><Input className="pl-10" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search symbol or strategy..."/></div><Select className="w-36" value={side} onChange={e=>setSide(e.target.value)}><option value="all">All directions</option><option value="buy">Buy</option><option value="sell">Sell</option></Select><Select className="w-36" value={result} onChange={e=>setResult(e.target.value)}><option value="all">All results</option><option value="win">Win</option><option value="loss">Loss</option></Select></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left"><thead><tr className="border-b border-border text-[10px] uppercase tracking-wider text-muted">{["Date","Symbol","Side","Strategy","Size","Entry","Exit","Result","RR","P/L"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map(t=><tr key={t.id} className="hover:bg-white/[.018]"><td className="px-3 py-4 text-xs text-muted">{t.date}</td><td className="px-3 py-4 font-extrabold"><Link href={"/journal/"+t.id} className="hover:text-primary">{t.symbol}</Link><span className="block text-[9px] font-normal text-muted">{t.timeframe} · {t.session}</span></td><td className="px-3 py-4"><Pill tone={t.direction==="buy"?"profit":"loss"}>{t.direction}</Pill></td><td className="px-3 py-4 text-xs">{t.strategy}</td><td className="px-3 py-4 text-xs">{t.lot}</td><td className="px-3 py-4 text-xs">{t.entry}</td><td className="px-3 py-4 text-xs">{t.exit||"—"}</td><td className="px-3 py-4"><Pill tone={t.status==="win"?"profit":t.status==="loss"?"loss":"neutral"}>{t.status}</Pill></td><td className="px-3 py-4 text-xs font-bold">{t.rr.toFixed(2)}R</td><td className={"px-3 py-4 text-sm font-extrabold "+(t.pnl>=0?"text-bullish":"text-bearish")}>{t.pnl>=0?"+":""}{money(t.pnl)}</td></tr>)}</tbody></table></div>
 <div className="mt-5 flex items-center justify-between border-t border-border pt-4"><p className="text-xs text-muted">Showing {rows.length} of {filtered.length}</p><div className="flex items-center gap-2"><Button kind="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="text-xs text-muted">{page} / {pages}</span><Button kind="secondary" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div></Card></div>
}