"use client";
import {FormEvent,useMemo,useState} from "react";
import {Calculator,CheckCircle2,ImagePlus,LoaderCircle,Save} from "lucide-react";
import type {Account,Strategy} from "@/types";
import {browserClient,configured} from "@/lib/supabase";
import {Button,Card,Input,Label,Select,Textarea} from "@/components/ui";
import {money} from "@/lib/utils";
export function TradeForm({accounts,strategies,isDemo}:{accounts:Account[];strategies:Strategy[];isDemo:boolean}){
 const[side,setSide]=useState<"buy"|"sell">("buy"),[entry,setEntry]=useState(0),[exit,setExit]=useState(0),[sl,setSl]=useState(0),[lot,setLot]=useState(1),[manual,setManual]=useState(false),[manualPnl,setManualPnl]=useState(0),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 const calc=useMemo(()=>{const move=(exit-entry)*(side==="buy"?1:-1),risk=Math.abs(entry-sl);return{pnl:manual?manualPnl:move*lot,rr:risk?move/risk:0,points:move}},[side,entry,exit,sl,lot,manual,manualPnl]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);try{if(!isDemo&&configured()){const sb=browserClient(),{data}=await sb.auth.getClaims(),user=data?.claims?.sub;if(!user)throw new Error("Session expired");const tradeId=crypto.randomUUID();const payload={id:tradeId,user_id:user,trading_account_id:f.get("account"),strategy_id:f.get("strategy")||null,symbol:String(f.get("symbol")).toUpperCase(),direction:side,status:calc.pnl>0?"win":calc.pnl<0?"loss":"breakeven",entry_price:Number(f.get("entry")),exit_price:Number(f.get("exit"))||null,stop_loss:Number(f.get("sl"))||null,take_profit:Number(f.get("tp"))||null,lot_size:Number(f.get("lot")),risk_percent:Number(f.get("risk"))||null,risk_amount:Number(f.get("risk_amount"))||null,pnl:calc.pnl,rr:calc.rr,points:calc.points,trade_date:f.get("date"),entry_time:f.get("entry_time")||null,exit_time:f.get("exit_time")||null,timeframe:f.get("timeframe"),session:f.get("session"),emotion:f.get("emotion"),confidence:Number(f.get("confidence"))||null,rating:Number(f.get("rating"))||null,setup:f.get("setup")||null,notes:f.get("notes")||null,tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),is_manual_pnl:manual};const{error}=await sb.from("trades").insert(payload);if(error)throw error;for(const kind of ["before","after"] as const){const file=f.get(kind);if(file instanceof File&&file.size){const ext=file.name.split(".").pop()||"jpg",path=user+"/"+tradeId+"/"+kind+"."+ext,{error:uploadError}=await sb.storage.from("trade-screenshots").upload(path,file,{contentType:file.type,upsert:true});if(uploadError)throw uploadError;const{error:rowError}=await sb.from("trade_screenshots").insert({user_id:user,trade_id:tradeId,storage_path:path,screenshot_type:kind});if(rowError)throw rowError}}}setNotice(isDemo?"Demo trade saved for preview. Connect Supabase to persist it.":"Trade saved successfully.")}catch(x){setNotice(x instanceof Error?x.message:"Could not save trade")}finally{setSaving(false)}}
 return <form onSubmit={submit} className="space-y-5 animate-enter"><div className="flex flex-wrap items-end justify-between"><div><h2 className="text-2xl font-extrabold">Log a new trade</h2><p className="mt-1 text-sm text-muted">Record the execution and decision context.</p></div><Button disabled={saving}>{saving?<LoaderCircle className="animate-spin" size={16}/>:<Save size={16}/>}Save trade</Button></div>{notice&&<div className="flex gap-2 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm"><CheckCircle2 size={16} className="text-bullish"/>{notice}</div>}
 <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><Card className="p-5"><h3 className="mb-5 text-sm font-bold">Trade execution</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><Label>Account</Label><Select name="account">{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></div><div><Label>Symbol</Label><Input name="symbol" placeholder="XAUUSD" required/></div><div><Label>Direction</Label><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setSide("buy")} className={"h-11 rounded-xl border font-bold "+(side==="buy"?"border-bullish bg-bullish/10 text-bullish":"border-border")}>BUY</button><button type="button" onClick={()=>setSide("sell")} className={"h-11 rounded-xl border font-bold "+(side==="sell"?"border-bearish bg-bearish/10 text-bearish":"border-border")}>SELL</button></div></div><div><Label>Entry</Label><Input name="entry" type="number" step="any" required onChange={e=>setEntry(+e.target.value)}/></div><div><Label>Exit</Label><Input name="exit" type="number" step="any" onChange={e=>setExit(+e.target.value)}/></div><div><Label>Lot size</Label><Input name="lot" type="number" step="any" defaultValue="1" onChange={e=>setLot(+e.target.value)}/></div><div><Label>Stop loss</Label><Input name="sl" type="number" step="any" onChange={e=>setSl(+e.target.value)}/></div><div><Label>Take profit</Label><Input name="tp" type="number" step="any"/></div><div><Label>Strategy</Label><Select name="strategy"><option value="">No strategy</option>{strategies.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></div></div></Card>
 <Card className="p-5"><h3 className="mb-5 text-sm font-bold">Risk, context, and psychology</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><Label>Risk %</Label><Input name="risk" type="number" step=".01"/></div><div><Label>Risk amount</Label><Input name="risk_amount" type="number" step=".01"/></div><div><Label>Date</Label><Input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></div><div><Label>Timeframe</Label><Select name="timeframe">{["M5","M15","H1","H4","D1"].map(x=><option key={x}>{x}</option>)}</Select></div><div><Label>Entry time</Label><Input name="entry_time" type="time"/></div><div><Label>Exit time</Label><Input name="exit_time" type="time"/></div><div><Label>Session</Label><Select name="session">{["asia","london","new_york","overlap","other"].map(x=><option key={x}>{x}</option>)}</Select></div><div><Label>Emotion</Label><Select name="emotion">{["calm","confident","fear","fomo","greed","angry","revenge","unsure"].map(x=><option key={x}>{x}</option>)}</Select></div><div><Label>Confidence</Label><Input name="confidence" type="number" min="1" max="10" defaultValue="7"/></div><div><Label>Rating</Label><Input name="rating" type="number" min="1" max="5" defaultValue="4"/></div><div className="sm:col-span-2"><Label>Tags</Label><Input name="tags" placeholder="A-setup, trend"/></div><div className="sm:col-span-2 lg:col-span-4"><Label>Setup</Label><Input name="setup" placeholder="Liquidity sweep + retest"/></div><div className="sm:col-span-2 lg:col-span-4"><Label>Notes</Label><Textarea name="notes" placeholder="What did you see, decide, and learn?"/></div></div></Card>
 <Card className="p-5"><h3 className="mb-4 text-sm font-bold">Chart screenshots</h3><div className="grid gap-3 sm:grid-cols-2">{["Before trade","After trade"].map((x,i)=><label key={x} className="grid min-h-28 cursor-pointer place-items-center rounded-xl border border-dashed border-border bg-[#0C1017] text-center"><span><ImagePlus className="mx-auto text-primary" size={20}/><b className="mt-2 block text-xs">{x}</b><small className="text-muted">PNG, JPG, WEBP</small></span><input name={i===0?"before":"after"} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp"/></label>)}</div></Card></div>
 <div><Card className="sticky top-24 p-5"><h3 className="flex gap-2 text-sm font-bold"><Calculator size={16} className="text-primary"/>Live calculation</h3><div className="mt-5 space-y-4">{[["Profit / Loss",money(calc.pnl)],["Risk reward",calc.rr.toFixed(2)+"R"],["Points / pips",calc.points.toFixed(2)]].map(([l,v])=><div key={l} className="flex justify-between border-b border-border pb-4"><span className="text-xs text-muted">{l}</span><b>{v}</b></div>)}</div><label className="mt-4 flex gap-2 text-xs text-muted"><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)} className="accent-primary"/>Override P/L</label>{manual&&<Input className="mt-3" type="number" step=".01" onChange={e=>setManualPnl(+e.target.value)}/>}</Card></div></div></form>
}