import type {ButtonHTMLAttributes,HTMLAttributes,InputHTMLAttributes,SelectHTMLAttributes,TextareaHTMLAttributes} from "react";
import {cn} from "@/lib/utils";
export function Button({className,kind="primary",...p}:ButtonHTMLAttributes<HTMLButtonElement>&{kind?:"primary"|"secondary"|"ghost"|"danger"}){return <button className={cn("inline-flex h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition disabled:opacity-50",kind==="primary"&&"bg-primary text-white shadow-[0_8px_28px_rgba(79,124,255,.24)] hover:bg-primary/90",kind==="secondary"&&"border border-border bg-surface-2 text-white hover:bg-surface-3",kind==="ghost"&&"text-muted hover:bg-white/5 hover:text-white",kind==="danger"&&"bg-bearish/10 text-bearish",className)} {...p}/>}
export function Card({className,...p}:HTMLAttributes<HTMLDivElement>){return <div className={cn("rounded-2xl border border-border bg-surface/90 shadow-[0_20px_60px_rgba(0,0,0,.16)]",className)} {...p}/>}
export function Input({className,...p}:InputHTMLAttributes<HTMLInputElement>){return <input className={cn("h-11 w-full rounded-xl border border-border bg-[#0C1017] px-3.5 text-sm text-white outline-none focus:border-primary/60",className)} {...p}/>}
export function Select({className,...p}:SelectHTMLAttributes<HTMLSelectElement>){return <select className={cn("h-11 w-full rounded-xl border border-border bg-[#0C1017] px-3.5 text-sm text-white outline-none focus:border-primary/60",className)} {...p}/>}
export function Textarea({className,...p}:TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea className={cn("min-h-28 w-full rounded-xl border border-border bg-[#0C1017] px-3.5 py-3 text-sm text-white outline-none focus:border-primary/60",className)} {...p}/>}
export function Label({children}:{children:React.ReactNode}){return <label className="mb-2 block text-xs font-medium text-muted">{children}</label>}
export function Pill({children,tone="neutral"}:{children:React.ReactNode;tone?:"profit"|"loss"|"neutral"|"info"}){return <span className={cn("inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold capitalize",tone==="profit"&&"border-bullish/20 bg-bullish/10 text-bullish",tone==="loss"&&"border-bearish/20 bg-bearish/10 text-bearish",tone==="info"&&"border-primary/20 bg-primary/10 text-[#9AB0FF]",tone==="neutral"&&"border-border text-muted")}>{children}</span>}
