import OpenAI from "openai";
import {NextResponse} from "next/server";
import {configured,serverClient} from "@/lib/supabase";
import {trades as demoTrades} from "@/lib/demo";
import {stats} from "@/lib/utils";
import type {Trade} from "@/types";
export const runtime="nodejs";
function safeContext(trades:Trade[]){const s=stats(trades),group=(key:(t:Trade)=>string)=>Object.values(trades.reduce<Record<string,{name:string;trades:number;wins:number;rr:number}>>((a,t)=>{const n=key(t)||"Unknown",r=a[n]||{name:n,trades:0,wins:0,rr:0};r.trades++;r.wins+=t.pnl>0?1:0;r.rr+=t.rr;a[n]=r;return a},{})).map(r=>({name:r.name,trades:r.trades,winRate:r.trades?r.wins/r.trades*100:0,averageRR:r.trades?r.rr/r.trades:0}));return{totalTrades:s.totalTrades,winRate:s.winRate,profitFactor:s.profitFactor,averageRR:s.averageRR,winningStreak:s.winStreak,losingStreak:s.lossStreak,symbols:group(t=>t.symbol),strategies:group(t=>t.strategy),sessions:group(t=>t.session),emotions:group(t=>t.emotion)}}
function localContext(trades:Trade[]){const safe=safeContext(trades),best=[...trades].reduce<Record<string,number>>((a,t)=>{a[t.symbol]=(a[t.symbol]||0)+t.pnl;return a},{}),bestSymbol=Object.entries(best).sort((a,b)=>b[1]-a[1])[0]?.[0]||"Not enough data";return{...safe,bestSymbol}}
function fallback(trades:Trade[],mode:string){const c=localContext(trades);return "## "+(mode==="weekly_review"?"Weekly Performance Review":mode==="monthly_review"?"Monthly Performance Review":"AI Trading Insight")+"\n\nYour journal contains **"+c.totalTrades+" trades** with a **"+c.winRate.toFixed(1)+"% win rate**, **"+c.profitFactor.toFixed(2)+" profit factor**, and **"+c.averageRR.toFixed(2)+"R average RR**.\n\n### Detected patterns\n- "+c.bestSymbol+" is currently the leading symbol by local net performance.\n- Longest winning streak: "+c.winningStreak+" trades; longest losing streak: "+c.losingStreak+" trades.\n- Compare sessions and strategies only after the sample contains enough repeated trades.\n\n### Risk plan\n1. Keep risk per trade fixed and below your written maximum.\n2. Stop after consecutive losses or after the third low-quality trade.\n3. Log emotion and entry confirmation consistently.\n\n*Performance coaching only—not a BUY/SELL signal or financial advice.*"}
export async function POST(request:Request){try{const body=await request.json(),message=String(body.message||"").slice(0,2000),mode=String(body.mode||"chat"),share=body.shareWithOpenAI===true;if(!message)return NextResponse.json({error:"Message is required"},{status:400});let trades:Trade[]=demoTrades,user="demo";let sb:Awaited<ReturnType<typeof serverClient>>|null=null;if(configured()&&process.env.NEXT_PUBLIC_DEMO_MODE!=="true"){sb=await serverClient();const{data:claims}=await sb.auth.getClaims();if(!claims?.claims?.sub)return NextResponse.json({error:"Unauthorized"},{status:401});user=claims.claims.sub;const{data}=await sb.from("trades").select("symbol,direction,status,pnl,rr,risk_percent,strategy:strategies(name),session,emotion");trades=(data||[]).map((x,i)=>({id:String(i),date:"",symbol:x.symbol,direction:x.direction,status:x.status,entry:0,exit:null,sl:null,tp:null,lot:0,risk:Number(x.risk_percent||0),pnl:Number(x.pnl),rr:Number(x.rr||0),strategy:x.strategy?.[0]?.name||"No strategy",session:x.session||"other",timeframe:"",emotion:x.emotion||"",notes:"",tags:[]}))}if(!trades.length)return NextResponse.json({answer:"Add at least one trade before requesting journal-grounded analysis."});let answer=fallback(trades,mode),provider="local";if(share&&process.env.OPENAI_API_KEY){const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY}),response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5.6",store:false,instructions:"You are FomoTrade AI, a trading performance coach. You only receive privacy-minimized aggregate statistics. Never provide direct BUY/SELL signals or guarantees. Distinguish correlation from causation, mention sample-size limits, answer in the user's language, and use concise Markdown.",input:"Mode: "+mode+"\nQuestion: "+message+"\nPrivacy-minimized aggregate statistics: "+JSON.stringify(safeContext(trades))});answer=response.output_text||answer;provider="openai"}if(sb)await sb.from("ai_analysis").insert({user_id:user,analysis_type:mode,input_summary:{trade_count:trades.length,provider},content:answer,model:provider==="openai"?(process.env.OPENAI_MODEL||"gpt-5.6"):"local-fallback"});return NextResponse.json({answer,provider})}catch(error){console.error(error);return NextResponse.json({error:"AI analysis could not be completed."},{status:500})}}